In [48]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Crear Vectores uni-, bi- o multi- dimensionales 

In [49]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [50]:
np.array([[1,2],[3,4], [5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
np.array([[[1,2,3], [1,2,3]],[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

### Vector cero

In [52]:
np.zeros(3)

array([0., 0., 0.])

In [53]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### Dimensión de Arrays

In [55]:
np.shape(np.array([1,2,3,4]))

(4,)

### Acceso a Arrays

In [56]:
x = np.array([[1,2],[3,4], [5,6]])
x[0]
x[0,1]

array([1, 2])

2

In [57]:
np.array([[1,2,3,4],[3,4,5,6], [2,3,3,4]])[0:3]

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [2, 3, 3, 4]])

### Operaciones

In [58]:
x = np.array([[1,2,3,4],[3,4,5,6]])
np.sum(x)
np.sum(x, axis=1)
x - x
x - x[1]
np.abs(x - x[1])

28

array([10, 18])

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

array([[-2, -2, -2, -2],
       [ 0,  0,  0,  0]])

array([[2, 2, 2, 2],
       [0, 0, 0, 0]])

In [59]:
x = np.array([[[1,2,3],[3,4,5]], [[1,2,3], [3,4,5]]])
np.sum(x, axis=0)
np.sum(x, axis=1)
np.sum(x, axis=2)

array([[ 2,  4,  6],
       [ 6,  8, 10]])

array([[4, 6, 8],
       [4, 6, 8]])

array([[ 6, 12],
       [ 6, 12]])

In [60]:
 np.argmin(np.array([13,11,12]))

1

In [61]:
!ipython nbconvert --to=python "Numpy Test.ipynb"

[TerminalIPythonApp] WARNING | Subcommand `ipython nbconvert` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter nbconvert` in the future
[NbConvertApp] Converting notebook Numpy Test.ipynb to python
[NbConvertApp] Writing 992 bytes to Numpy Test.py
