In [1]:
import numpy as np

### Crear Vectores uni-, bi- o multi- dimensionales 

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
np.array([[1,2],[3,4], [5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
np.array([[[1,2,3], [1,2,3]],[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

### Vector cero

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### Dimensión de Arrays

In [8]:
np.shape(np.array([1,2,3,4]))

(4,)

### Acceso a Arrays

In [9]:
x = np.array([[1,2],[3,4], [5,6]])
x[0]
x[0,1]

2

In [10]:
np.array([[1,2,3,4],[3,4,5,6], [2,3,3,4]])[0:3]

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [2, 3, 3, 4]])

### Operaciones

In [11]:
x = np.array([[1,2,3,4],[3,4,5,6]])
np.sum(x)
np.sum(x, axis=1)
x - x
x - x[1]
np.abs(x - x[1])

array([[2, 2, 2, 2],
       [0, 0, 0, 0]])

In [12]:
x = np.array([[[1,2,3],[3,4,5]], [[1,2,3], [3,4,5]]])
np.sum(x, axis=0)
np.sum(x, axis=1)
np.sum(x, axis=2)

array([[ 6, 12],
       [ 6, 12]])

In [13]:
 np.argmin(np.array([13,11,12]))

1

In [14]:
!ipython nbconvert --to=python "Numpy Test.ipynb"

[TerminalIPythonApp] WARNING | Subcommand `ipython nbconvert` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter nbconvert` in the future
[NbConvertApp] Converting notebook Numpy Test.ipynb to python
[NbConvertApp] Writing 977 bytes to Numpy Test.py
